from datetime import datetime,timezone
import uuid
NOW=lambda:datetime.now(timezone.utc).isoformat()
def product(c,h,s,name,tracked=True):return c.post(f"/api/shops/{s['id']}/products",headers=h,json={'name':name,'unit':'piece','inventory_enabled':tracked,'active':True,'buy_price':'10','sell_price':'20'}).json()
def post(c,h,s,body):return c.post(f"/api/shops/{s['id']}/transactions",headers=h,json={'occurred_at':NOW(),**body})
def test_atomic_credit_sale_idempotency_and_failure_rollback(client,owner):
    h,s=owner;p=product(client,h,s,'Tracked');customer=client.post(f"/api/shops/{s['id']}/customers",headers=h,json={'name':'Ravi'}).json();supplier=client.post(f"/api/shops/{s['id']}/suppliers",headers=h,json={'name':'Dealer'}).json()
    purchase={'type':'purchase','amount':'10','payment_method':'cash','payment_state':'paid','paid_amount':'10','supplier_id':supplier['id'],'idempotency_key':str(uuid.uuid4()),'items':[{'product_id':p['id'],'quantity':'1','unit_price':'10'}]};assert post(client,h,s,purchase).status_code==201
    key=str(uuid.uuid4());sale={'type':'sale','amount':'20','payment_method':'credit','customer_id':customer['id'],'idempotency_key':key,'items':[{'product_id':p['id'],'quantity':'1','unit_price':'20','cost_price':'10'}]};a=post(client,h,s,sale);b=post(client,h,s,sale);assert a.status_code==201 and b.status_code==201 and a.json()['id']==b.json()['id']
    assert client.get(f"/api/shops/{s['id']}/inventory",headers=h).json()[0]['stock']==0;detail=client.get(f"/api/shops/{s['id']}/customers/{customer['id']}",headers=h).json();assert detail['balance']==20 and len(detail['entries'])==1
    other_token=client.post('/api/auth/register',json={'email':'atomic@example.com','password':'password1','name':'Other'}).json()['access_token'];oh={'Authorization':f'Bearer {other_token}'};os=client.post('/api/shops',headers=oh,json={'name':'Other'}).json();foreign=product(client,oh,os,'Foreign',False)
    before=len(client.get(f"/api/shops/{s['id']}/transactions",headers=h).json());bad={**purchase,'idempotency_key':str(uuid.uuid4()),'amount':'20','items':[{'product_id':p['id'],'quantity':'1','unit_price':'10'},{'product_id':foreign['id'],'quantity':'1','unit_price':'10'}]};assert post(client,h,s,bad).status_code==409;assert len(client.get(f"/api/shops/{s['id']}/transactions",headers=h).json())==before
    p2=product(client,h,s,'Sale rollback');seed={**purchase,'idempotency_key':str(uuid.uuid4()),'amount':'20','items':[{'product_id':p2['id'],'quantity':'2','unit_price':'10'}]};assert post(client,h,s,seed).status_code==201;before_due=client.get(f"/api/shops/{s['id']}/customers/{customer['id']}",headers=h).json()['balance'];bad_sale={**sale,'idempotency_key':str(uuid.uuid4()),'amount':'30','items':[{'product_id':p2['id'],'quantity':'1','unit_price':'20'},{'product_id':foreign['id'],'quantity':'1','unit_price':'10'}]};assert post(client,h,s,bad_sale).status_code==409;stocks={x['product_id']:x['stock'] for x in client.get(f"/api/shops/{s['id']}/inventory",headers=h).json()};assert stocks[p2['id']]==2 and client.get(f"/api/shops/{s['id']}/customers/{customer['id']}",headers=h).json()['balance']==before_due
def test_expense_and_stock_idempotency(client,owner):
    h,s=owner;key=str(uuid.uuid4());expense={'type':'expense','amount':'99.99','payment_method':'cash','category':'Power','idempotency_key':key,'items':[]};assert post(client,h,s,expense).json()['id']==post(client,h,s,expense).json()['id'];assert len(client.get(f"/api/shops/{s['id']}/transactions?type=expense",headers=h).json())==1
    p=product(client,h,s,'Stock');k=str(uuid.uuid4());body={'quantity_difference':'2.5','reason':'Opening count','occurred_at':NOW(),'idempotency_key':k};url=f"/api/shops/{s['id']}/inventory/{p['id']}/adjustments";assert client.post(url,headers=h,json=body).json()['id']==client.post(url,headers=h,json=body).json()['id'];assert client.get(f"/api/shops/{s['id']}/inventory",headers=h).json()[0]['stock']==2.5
