from datetime import date,datetime,timezone
NOW=lambda:datetime.now(timezone.utc).isoformat()
def test_complete_shop_workflow(client):
    token=client.post('/api/auth/register',json={'email':'demo@nadha.in','password':'demopass1','name':'Anita'}).json()['access_token'];h={'Authorization':f'Bearer {token}'};s=client.post('/api/shops',headers=h,json={'name':'Anita General Store','phone':'9999999999','business_type':'general store'}).json();base=f"/api/shops/{s['id']}"
    def tx(body):return client.post(base+'/transactions',headers=h,json={'occurred_at':NOW(),**body}).json()
    tx({'type':'sale','amount':'500','payment_method':'cash'});tx({'type':'sale','amount':'300','payment_method':'upi'})
    customer=client.post(base+'/customers',headers=h,json={'name':'Ravi'}).json();tx({'type':'sale','amount':'800','payment_method':'credit','customer_id':customer['id']});client.post(base+f"/customers/{customer['id']}/payments",headers=h,json={'amount':'200','occurred_at':NOW()})
    supplier=client.post(base+'/suppliers',headers=h,json={'name':'ABC Distributor','payment_terms':'30 days'}).json();purchase=tx({'type':'purchase','amount':'1000','payment_method':'cash','payment_state':'due','paid_amount':'0','supplier_id':supplier['id']});client.post(base+f"/suppliers/{supplier['id']}/payments",headers=h,json={'amount':'250','occurred_at':NOW()});tx({'type':'expense','amount':'100','payment_method':'cash','category':'Transport'})
    client.post(base+'/closings',headers=h,json={'date':date.today().isoformat(),'actual_cash':'400'})
    later=tx({'type':'sale','amount':'260','payment_method':'cash'});product=client.post(base+'/products',headers=h,json={'name':'Sunflower Oil','unit':'litre','buy_price':'100','sell_price':'130','inventory_enabled':True,'active':True}).json();client.put(base+f"/transactions/{later['id']}/items",headers=h,json=[{'product_id':product['id'],'quantity':'2','unit_price':'130','cost_price':'100'}]);client.put(base+f"/transactions/{purchase['id']}/items",headers=h,json=[{'product_id':product['id'],'quantity':'10','unit_price':'100','cost_price':'100'}])
    assert client.get(base+'/inventory',headers=h).json()[0]['stock']==8;assert client.get(base+'/profit',headers=h).status_code==200
    client.post(base+'/lost-sales',headers=h,json={'requested_product':'2L Cooking Oil','quantity':'1','occurred_at':NOW()});assert client.get(base+'/shop-health?period=today',headers=h).status_code==200;assert client.get(base+'/collect-today',headers=h).json()['priorities'];assert client.get(base+f"/products/{product['id']}/supplier-prices",headers=h).json()
    review=client.get(base+'/cash-review?period=today',headers=h).json();assert review['dates'];body={k:v for k,v in later.items() if k not in ('id','shop_id','created_at','updated_at')};body['amount']='270';client.put(base+f"/transactions/{later['id']}",headers=h,json=body);assert client.get(base+'/cash-review?period=today',headers=h).json()['dates'][0]['difference']!=review['dates'][0]['difference'];assert len(client.get(base+'/audit',headers=h).json())>=8
