"""paid intelligence and money control
Revision ID: fe6f793fd07e
Revises: a96b14f88e64
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'fe6f793fd07e'
down_revision: Union[str, None] = 'a96b14f88e64'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_shop_id'), 'audit_logs', ['shop_id'], unique=False)
    op.create_index('ix_audit_shop_entity_date', 'audit_logs', ['shop_id', 'entity', 'created_at'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('references_json', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insights_shop_created', 'insights', ['shop_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_insights_shop_id'), 'insights', ['shop_id'], unique=False)
    op.create_table('lost_sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('requested_product', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_product_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['converted_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_sales_customer_id'), 'lost_sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_lost_sales_occurred_at'), 'lost_sales', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_lost_sales_shop_id'), 'lost_sales', ['shop_id'], unique=False)
    op.create_index('ix_lost_sales_shop_requested_date', 'lost_sales', ['shop_id', 'requested_product', 'occurred_at'], unique=False)
    op.create_index('ix_inventory_shop_product_date', 'inventory_movements', ['shop_id', 'product_id', 'occurred_at'], unique=False)
    op.create_index('ix_ledger_shop_customer_date', 'ledger_entries', ['shop_id', 'customer_id', 'occurred_at'], unique=False)
    op.create_index('ix_ledger_shop_supplier_date', 'ledger_entries', ['shop_id', 'supplier_id', 'occurred_at'], unique=False)
    op.add_column('suppliers', sa.Column('payment_terms', sa.String(length=160), nullable=True))
    op.add_column('transaction_items', sa.Column('product_name_snapshot', sa.String(length=160), nullable=False, server_default=''))
    op.add_column('transaction_items', sa.Column('supplier_name_snapshot', sa.String(length=160), nullable=True))
    op.execute("UPDATE transaction_items SET product_name_snapshot = COALESCE((SELECT name FROM products WHERE products.id = transaction_items.product_id), '')")
    op.execute("UPDATE transaction_items SET supplier_name_snapshot = (SELECT suppliers.name FROM transactions JOIN suppliers ON suppliers.id = transactions.supplier_id WHERE transactions.id = transaction_items.transaction_id)")
    op.create_index('ix_transactions_shop_type_occurred', 'transactions', ['shop_id', 'type', 'occurred_at'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_shop_type_occurred', table_name='transactions')
    op.drop_column('transaction_items', 'supplier_name_snapshot')
    op.drop_column('transaction_items', 'product_name_snapshot')
    op.drop_column('suppliers', 'payment_terms')
    op.drop_index('ix_ledger_shop_supplier_date', table_name='ledger_entries')
    op.drop_index('ix_ledger_shop_customer_date', table_name='ledger_entries')
    op.drop_index('ix_inventory_shop_product_date', table_name='inventory_movements')
    op.drop_index('ix_lost_sales_shop_requested_date', table_name='lost_sales')
    op.drop_index(op.f('ix_lost_sales_shop_id'), table_name='lost_sales')
    op.drop_index(op.f('ix_lost_sales_occurred_at'), table_name='lost_sales')
    op.drop_index(op.f('ix_lost_sales_customer_id'), table_name='lost_sales')
    op.drop_table('lost_sales')
    op.drop_index(op.f('ix_insights_shop_id'), table_name='insights')
    op.drop_index('ix_insights_shop_created', table_name='insights')
    op.drop_table('insights')
    op.drop_index('ix_audit_shop_entity_date', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_shop_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
