import{useEffect,useRef,useState}from'react';import{App as CapacitorApp}from'@capacitor/app';import{Capacitor}from'@capacitor/core';import{api,errorKey}from'./api/client';import{useI18n}from'./i18n';import{Auth}from'./pages/Auth';import{Home}from'./pages/Home';import{Entry}from'./pages/Entry';import{People}from'./pages/People';import{Diary}from'./pages/Diary';import{Credit}from'./pages/Credit';import{Settings}from'./pages/Settings';import{Spinner,StatusMessage}from'./components/ui';
export type Shop={id:string;name:string;timezone:string;ai_enabled:boolean};export type Page='home'|'add'|'credit'|'people'|'diary'|'settings';
const validPages:Page[]=['home','add','credit','people','diary','settings'];
function readPage():Page{const value=location.hash.slice(1)as Page;return validPages.includes(value)?value:'home'}
export function App(){const{t}=useI18n();const[shop,setShop]=useState<Shop|null>(null),[ready,setReady]=useState(false),[page,setPage]=useState<Page>(readPage),[refresh,setRefresh]=useState(0),[startupError,setStartupError]=useState(''),[exitHint,setExitHint]=useState(false),lastBack=useRef(0);const signedIn=Boolean(localStorage.getItem('token'));
  const loadShop=()=>{setStartupError('');setReady(false);if(!localStorage.getItem('token')){setReady(true);return}api<Shop[]>('/shops').then(x=>setShop(x[0]||null)).catch(e=>setStartupError(errorKey(e))).finally(()=>setReady(true))};
  useEffect(()=>{loadShop();const hash=()=>setPage(readPage());const expired=()=>{setShop(null);setReady(true)};addEventListener('hashchange',hash);addEventListener('nadha:session-expired',expired);return()=>{removeEventListener('hashchange',hash);removeEventListener('nadha:session-expired',expired)}},[]);
  useEffect(()=>{if(!Capacitor.isNativePlatform())return;let active=true;const registration=CapacitorApp.addListener('backButton',()=>{if(page!=='home'){location.hash='home';setExitHint(false);return}const now=Date.now();if(now-lastBack.current<=2000){CapacitorApp.exitApp();return}lastBack.current=now;setExitHint(true);window.setTimeout(()=>{if(active)setExitHint(false)},2000)});return()=>{active=false;registration.then(x=>x.remove())}},[page]);
  function navigate(next:Page){if(next===page)return;location.hash=next}
  if(!ready)return <div className="center"><Spinner label={t('status.loadingPage')}/></div>;
  if(!signedIn||!shop){if(startupError&&signedIn)return <div className="center state-page"><StatusMessage>{t(startupError as never)}</StatusMessage><button className="primary" onClick={loadShop}>{t('common.retry')}</button></div>;return <Auth onReady={s=>{setShop(s);location.hash='home'}}/>}
  const pages={home:<Home shop={shop} refresh={refresh}/>,add:<Entry shop={shop} done={()=>{setRefresh(x=>x+1);navigate('home')}}/>,credit:<Credit shop={shop} refresh={refresh}/>,people:<People shop={shop} refresh={()=>setRefresh(x=>x+1)}/>,diary:<Diary shop={shop} refresh={refresh}/>,settings:<Settings shop={shop} onLogout={()=>{setShop(null);location.hash='home'}}/>};
  const titles:Record<Page,string>={home:shop.name,add:t('nav.sale'),credit:t('credit.title'),people:t('people.title'),diary:'ഡയറി',settings:t('settings.title')};const nav:Array<[Page,string,string]>=[['home','⌂',t('nav.home')],['add','＋',t('nav.sale')],['credit','₹',t('nav.money')],['diary','▤','ഡയറി'],['settings','⋯',t('nav.more')]];
  return <div className="app"><header className="app-header"><div className="compact-brand" aria-hidden="true">N</div><h1>{titles[page]}</h1>{page!=='settings'?<button className="header-action" aria-label={t('settings.title')} onClick={()=>navigate('settings')}>⚙</button>:<span className="header-spacer"/>}</header><main key={page}>{pages[page]}</main><nav aria-label="Primary navigation">{nav.map(([p,icon,label])=><button type="button" aria-current={page===p?'page':undefined} className={page===p?'active':''} onClick={()=>navigate(p)} key={p}><span aria-hidden="true">{icon}</span><b>{label}</b></button>)}</nav>{exitHint&&<div className="exit-hint" role="status">Press back again to exit</div>}</div>}
