import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from 'react';

export type Language='en'|'ml';
export type Appearance='system'|'light'|'dark';
type Vars=Record<string,string|number>;

const en={
  'common.cancel':'Cancel','common.close':'Close','common.save':'Save','common.saved':'Saved','common.retry':'Try again','common.loading':'Loading…','common.optional':'optional','common.none':'None','common.add':'Add','common.edit':'Edit','common.delete':'Delete','common.deactivate':'Deactivate','common.back':'Back',
  'nav.home':'Home','nav.sale':'New sale','nav.money':'Payments','nav.items':'Items','nav.more':'More',
  'auth.title':'Nadha Merchant','auth.subtitle':'Your daily business, clearly recorded.','auth.name':'Your name','auth.shop':'Shop name','auth.email':'Email','auth.password':'Password','auth.create':'Create my shop','auth.login':'Log in','auth.haveAccount':'I already have an account','auth.newAccount':'Create a new account',
  'settings.title':'Settings','settings.app':'App','settings.language':'Language / ഭാഷ','settings.appearance':'Appearance','settings.english':'English','settings.malayalam':'മലയാളം','settings.system':'System','settings.light':'Light','settings.dark':'Dark','settings.business':'Business','settings.businessName':'Business name','settings.account':'Account','settings.signedIn':'Signed in securely','settings.support':'Support','settings.help':'Help','settings.about':'About Nadha Merchant','settings.version':'Version 1.0.0','settings.session':'Session','settings.logout':'Log out','settings.logoutTitle':'Log out?','settings.logoutBody':"You'll need to sign in again to access your business.",'settings.loggingOut':'Logging out…',
  'home.position':"Today's balance",'home.positionHelp':'Sales minus purchases and expenses','home.moneyMap':'Where is my money?','home.today':'Today','home.outstanding':'Payments due','home.sales':'Sales today','home.moneyReceived':'Money received','home.moneyPaid':'Money paid','home.creditSection':'Credit / പറ്റ്','home.channels':'Today’s money channels','home.purchases':'Purchases','home.expenses':'Expenses','home.cash':'Cash received','home.upi':'UPI received','home.cashPaid':'Cash paid','home.upiPaid':'UPI paid','home.supplierPaid':'Paid suppliers today','home.creditGiven':'Credit given today','home.creditCollected':'Credit collected today','home.customersOwe':'Customers owe me','home.suppliersOwe':'I owe suppliers','home.stockValue':'Estimated stock value','home.closeToday':'Close today','home.dayClosed':'Day closed','home.expectedCash':'Expected cash flow','home.actualCash':'Actual cash counted','home.notes':'Notes','home.saveClosing':'Save closing',
  'entry.title':'Add entry','entry.sale':'Sale','entry.purchase':'Purchase','entry.expense':'Expense','entry.amount':'Amount','entry.when':'When','entry.customer':'Customer','entry.supplier':'Supplier','entry.paymentStatus':'Payment status','entry.amountPaid':'Amount paid','entry.category':'Category','entry.paymentMethod':'Payment method','entry.note':'Note','entry.save':'Save {type}','entry.cash':'Cash','entry.credit':'Credit','entry.bank':'Bank','entry.paid':'Paid','entry.partial':'Partly paid','entry.due':'Due','entry.saved':'Entry saved',
  'people.title':'Customers & suppliers','people.customers':'Customers','people.suppliers':'Suppliers','people.products':'Products','people.new':'New','people.name':'Name','people.phone':'Phone','people.noPhone':'No phone number','people.emptyCustomers':'No customers yet','people.emptyCustomersHelp':'Add a customer when you make a credit sale.','people.emptySuppliers':'No suppliers yet','people.emptySuppliersHelp':'Add suppliers to keep track of purchases and payments.',
  'credit.title':'Payments','credit.collectToday':'Collect today','credit.toCollect':'To collect','credit.toPay':'To pay','credit.record':'Record payment','credit.tap':'Tap to record payment','credit.amount':'Amount','credit.note':'Note','credit.save':'Save payment','credit.empty':'No payments due','credit.emptyHelp':'Outstanding customer and supplier payments will appear here.','credit.saved':'Payment saved',
  'history.title':'History','history.all':'All','history.sales':'Sales','history.purchases':'Purchases','history.expenses':'Expenses','history.credit':'Credit','history.date':'Date','history.products':'Products','history.empty':'No entries here','history.emptyHelp':'Your saved sales, purchases, and expenses will appear here.','history.edit':'Edit entry','history.save':'Save changes',
  'products.title':'Products','products.new':'New product','products.hint':'Add products you bill or track regularly.','products.name':'Product name','products.buy':'Buy price','products.sell':'Sell price','products.unit':'Unit','products.track':'Track stock','products.create':'Add product','products.stock':'Stock {count}','products.empty':'No products yet','products.emptyHelp':'Add your first product to start itemised billing.','products.deactivateTitle':'Deactivate this product?','products.deactivateBody':'It will be hidden from active product lists. Existing sales records will stay unchanged.',
  'status.loadingPage':'Getting things ready…','status.errorTitle':'Couldn’t load this page','status.empty':'Nothing here yet',
  'errors.network':"Couldn't connect. Check your internet and try again.",'errors.session':'Your session has expired. Please sign in again.','errors.stock':'Not enough stock available. Check the quantity and try again.','errors.permission':"You don't have permission to do this.",'errors.notFound':"We couldn't find that item. Refresh and try again.",'errors.conflict':'That already exists. Check the details and try again.','errors.validation':'Check the highlighted details and try again.','errors.server':'Something went wrong. Please try again.','errors.unknown':'Something went wrong. Please try again.'
} as const;

const ml:Record<keyof typeof en,string>={
  'common.cancel':'വേണ്ട','common.close':'അടയ്ക്കുക','common.save':'സേവ് ചെയ്യുക','common.saved':'സേവ് ചെയ്തു','common.retry':'വീണ്ടും ശ്രമിക്കുക','common.loading':'ലോഡ് ചെയ്യുന്നു…','common.optional':'നിർബന്ധമില്ല','common.none':'ഒന്നുമില്ല','common.add':'ചേർക്കുക','common.edit':'തിരുത്തുക','common.delete':'കളയുക','common.deactivate':'നിർജ്ജീവമാക്കുക','common.back':'തിരികെ',
  'nav.home':'ഹോം','nav.sale':'പുതിയ Sale','nav.money':'Payment','nav.items':'Items','nav.more':'കൂടുതൽ',
  'auth.title':'Nadha Merchant','auth.subtitle':'നിങ്ങളുടെ കടയുടെ ദിവസക്കണക്ക്, എളുപ്പത്തിൽ.','auth.name':'നിങ്ങളുടെ പേര്','auth.shop':'കടയുടെ പേര്','auth.email':'Email','auth.password':'Password','auth.create':'എന്റെ കട തുടങ്ങുക','auth.login':'Log in','auth.haveAccount':'എനിക്ക് account ഉണ്ട്','auth.newAccount':'പുതിയ account തുടങ്ങുക',
  'settings.title':'Settings','settings.app':'App','settings.language':'Language / ഭാഷ','settings.appearance':'കാഴ്ച','settings.english':'English','settings.malayalam':'മലയാളം','settings.system':'ഫോണിന്റെ setting','settings.light':'Light','settings.dark':'Dark','settings.business':'കട','settings.businessName':'കടയുടെ പേര്','settings.account':'Account','settings.signedIn':'സുരക്ഷിതമായി sign in ചെയ്തിരിക്കുന്നു','settings.support':'സഹായം','settings.help':'Help','settings.about':'Nadha Merchant-നെ കുറിച്ച്','settings.version':'Version 1.0.0','settings.session':'Session','settings.logout':'Log out','settings.logoutTitle':'Log out ചെയ്യണോ?','settings.logoutBody':'കടയുടെ വിവരങ്ങൾ വീണ്ടും കാണാൻ sign in ചെയ്യേണ്ടിവരും.','settings.loggingOut':'Log out ചെയ്യുന്നു…',
  'home.position':'ഇന്നത്തെ ബാക്കി','home.positionHelp':'Sale-ൽ നിന്ന് purchase-ഉം expense-ഉം കുറച്ചത്','home.moneyMap':'എന്റെ പണം എവിടെയാണ്?','home.today':'ഇന്നത്തെ കണക്ക്','home.outstanding':'കിട്ടാനും കൊടുക്കാനുമുള്ളത്','home.sales':'ഇന്നത്തെ Sale','home.moneyReceived':'കിട്ടിയ പണം','home.moneyPaid':'കൊടുത്ത പണം','home.creditSection':'പറ്റ്','home.channels':'ഇന്നത്തെ പണമിടപാട്','home.purchases':'Purchases','home.expenses':'Expenses','home.cash':'കിട്ടിയ Cash','home.upi':'കിട്ടിയ UPI','home.cashPaid':'കൊടുത്ത Cash','home.upiPaid':'കൊടുത്ത UPI','home.supplierPaid':'Supplier-ന് കൊടുത്തത്','home.creditGiven':'ഇന്ന് പറ്റിൽ കൊടുത്തത്','home.creditCollected':'ഇന്ന് പറ്റ് കിട്ടിയത്','home.customersOwe':'എനിക്ക് കിട്ടാനുള്ളത്','home.suppliersOwe':'ഞാൻ കൊടുക്കാനുള്ളത്','home.stockValue':'Stock-ന്റെ ഏകദേശ വില','home.closeToday':'ഇന്നത്തെ കണക്ക് അടയ്ക്കുക','home.dayClosed':'കണക്ക് അടച്ചു','home.expectedCash':'ഇന്നത്തെ Cash വ്യത്യാസം','home.actualCash':'എണ്ണിയ Cash','home.notes':'കുറിപ്പ്','home.saveClosing':'കണക്ക് സേവ് ചെയ്യുക',
  'entry.title':'Entry ചേർക്കുക','entry.sale':'Sale','entry.purchase':'Purchase','entry.expense':'Expense','entry.amount':'തുക','entry.when':'സമയം','entry.customer':'Customer','entry.supplier':'Supplier','entry.paymentStatus':'Payment നില','entry.amountPaid':'കൊടുത്ത തുക','entry.category':'ഇനം','entry.paymentMethod':'Payment വഴി','entry.note':'കുറിപ്പ്','entry.save':'{type} സേവ് ചെയ്യുക','entry.cash':'Cash','entry.credit':'Credit','entry.bank':'Bank','entry.paid':'മുഴുവൻ കൊടുത്തു','entry.partial':'കുറച്ച് കൊടുത്തു','entry.due':'കൊടുക്കാനുണ്ട്','entry.saved':'Entry സേവ് ചെയ്തു',
  'people.title':'Customers & suppliers','people.customers':'Customers','people.suppliers':'Suppliers','people.products':'Products','people.new':'പുതിയത്','people.name':'പേര്','people.phone':'ഫോൺ','people.noPhone':'ഫോൺ നമ്പർ ഇല്ല','people.emptyCustomers':'Customers ഇല്ല','people.emptyCustomersHelp':'Credit sale ചെയ്യുമ്പോൾ customer-നെ ചേർക്കാം.','people.emptySuppliers':'Suppliers ഇല്ല','people.emptySuppliersHelp':'Purchase-ഉം payment-ഉം നോക്കാൻ supplier-നെ ചേർക്കുക.',
  'credit.title':'Payments','credit.collectToday':'ഇന്ന് പിരിക്കാനുള്ളത്','credit.toCollect':'കിട്ടാനുള്ളത്','credit.toPay':'കൊടുക്കാനുള്ളത്','credit.record':'Payment ചേർക്കുക','credit.tap':'Payment ചേർക്കാൻ അമർത്തുക','credit.amount':'തുക','credit.note':'കുറിപ്പ്','credit.save':'Payment സേവ് ചെയ്യുക','credit.empty':'Payment ഒന്നും ബാക്കിയില്ല','credit.emptyHelp':'കിട്ടാനും കൊടുക്കാനുമുള്ള തുക ഇവിടെ കാണാം.','credit.saved':'Payment സേവ് ചെയ്തു',
  'history.title':'പഴയ കണക്കുകൾ','history.all':'എല്ലാം','history.sales':'Sales','history.purchases':'Purchases','history.expenses':'Expenses','history.credit':'Credit','history.date':'തീയതി','history.products':'Products','history.empty':'Entry ഒന്നുമില്ല','history.emptyHelp':'സേവ് ചെയ്ത sale, purchase, expense ഇവിടെ കാണാം.','history.edit':'Entry തിരുത്തുക','history.save':'മാറ്റം സേവ് ചെയ്യുക',
  'products.title':'Products','products.new':'പുതിയ Product','products.hint':'പതിവായി bill ചെയ്യുന്നതോ stock നോക്കുന്നതോ ആയ products ചേർക്കുക.','products.name':'Product പേര്','products.buy':'വാങ്ങിയ വില','products.sell':'വിൽക്കുന്ന വില','products.unit':'Unit','products.track':'Stock നോക്കുക','products.create':'Product ചേർക്കുക','products.stock':'Stock {count}','products.empty':'Products ഇല്ല','products.emptyHelp':'Item Bill തുടങ്ങാൻ ആദ്യ product ചേർക്കുക.','products.deactivateTitle':'ഈ product നിർജ്ജീവമാക്കണോ?','products.deactivateBody':'Active product list-ൽ ഇനി കാണില്ല. പഴയ sale കണക്കുകൾ മാറ്റമില്ലാതെ ഇരിക്കും.',
  'status.loadingPage':'വിവരങ്ങൾ എടുക്കുന്നു…','status.errorTitle':'ഈ page തുറക്കാനായില്ല','status.empty':'ഇവിടെ ഒന്നുമില്ല',
  'errors.network':'Internet കിട്ടുന്നില്ല. Connection നോക്കി വീണ്ടും ശ്രമിക്കുക.','errors.session':'Session കഴിഞ്ഞു. വീണ്ടും sign in ചെയ്യുക.','errors.stock':'വേണ്ടത്ര stock ഇല്ല. എണ്ണം നോക്കി വീണ്ടും ശ്രമിക്കുക.','errors.permission':'ഇത് ചെയ്യാൻ നിങ്ങൾക്ക് അനുവാദമില്ല.','errors.notFound':'അത് കണ്ടെത്താനായില്ല. Refresh ചെയ്ത് വീണ്ടും ശ്രമിക്കുക.','errors.conflict':'ഇത് നേരത്തെ ചേർത്തിട്ടുണ്ട്. വിവരങ്ങൾ നോക്കി വീണ്ടും ശ്രമിക്കുക.','errors.validation':'നൽകിയ വിവരങ്ങൾ നോക്കി വീണ്ടും ശ്രമിക്കുക.','errors.server':'എന്തോ പ്രശ്നമുണ്ടായി. വീണ്ടും ശ്രമിക്കുക.','errors.unknown':'എന്തോ പ്രശ്നമുണ്ടായി. വീണ്ടും ശ്രമിക്കുക.'
};

type I18nContextValue={language:Language;setLanguage:(v:Language)=>void;appearance:Appearance;setAppearance:(v:Appearance)=>void;t:(key:keyof typeof en,vars?:Vars)=>string;locale:string};
const I18nContext=createContext<I18nContextValue|null>(null);

export function PreferencesProvider({children}:{children:ReactNode}){
  const[language,setLanguage]=useState<Language>(()=>localStorage.getItem('nadha.language')==='ml'?'ml':'en');
  const[appearance,setAppearance]=useState<Appearance>(()=>{const v=localStorage.getItem('nadha.appearance');return v==='light'||v==='dark'?v:'system'});
  useEffect(()=>{localStorage.setItem('nadha.language',language);document.documentElement.lang=language},[language]);
  useEffect(()=>{localStorage.setItem('nadha.appearance',appearance);const media=matchMedia('(prefers-color-scheme: dark)');const apply=()=>document.documentElement.dataset.theme=appearance==='system'?(media.matches?'dark':'light'):appearance;apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply)},[appearance]);
  const value=useMemo<I18nContextValue>(()=>({language,setLanguage,appearance,setAppearance,locale:language==='ml'?'ml-IN':'en-IN',t:(key,vars={})=>Object.entries(vars).reduce((s,[k,v])=>s.replaceAll(`{${k}}`,String(v)),(language==='ml'?ml[key]:en[key])||en[key]||key)}),[language,appearance]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(){const value=useContext(I18nContext);if(!value)throw new Error('useI18n must be used inside PreferencesProvider');return value}
export type TranslationKey=keyof typeof en;
